## code to prepare `pkg-dev` dataset goes here

usethis::use_data_raw("pkg-dev")
usethis::use_data_raw("nyt-get")
usethis::use_data_raw("nyt-wrangle")
usethis::use_mit_license("Michael W. Kearney")
usethis::use_readme_rmd(open = FALSE)
usethis::use_lifecycle_badge("experimental")
usethis::use_cran_badge()
usethis::use_git()
usethis::use_github()
usethis::use_travis()
usethis::use_travis_badge()
usethis::use_appveyor(FALSE)
devtools::document(roclets = c('rd', 'collate', 'namespace'))
usethis::use_news_md()
